# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(681, 594)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(681, 594))
        mainWindow.setMaximumSize(QtCore.QSize(681, 594))
        mainWindow.setStyleSheet("QLabel\n"
"{\n"
"  font-weight:bold;\n"
"  font-size: 16px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: gray;\n"
"}"
"QPushButton\n"
"{\n"
"  border: 2px solid gray;\n"
"  border-radius: 10px;\n"
"  padding: 0 8px;\n"
"  background: white;\n"
"  font-size: 20px;\n"
"}")
        mainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Stack = QtWidgets.QStackedWidget()
        mainWindow.setCentralWidget(self.Stack)
        self.Stack.addWidget(self.centralwidget)

        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.x1_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_label.setObjectName("x1_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.x1_label)
        self.x1_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.x1_lineEdit.setObjectName("x1_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.x1_lineEdit)
        self.x2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_label.setObjectName("x2_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.x2_label)
        self.x2_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.x2_lineEdit.setObjectName("x2_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.x2_lineEdit)
        self.x3_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_label.setObjectName("x3_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.x3_label)
        self.x3_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.x3_lineEdit.setObjectName("x3_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.x3_lineEdit)
        self.x4_label = QtWidgets.QLabel(self.centralwidget)
        self.x4_label.setObjectName("x4_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.x4_label)
        self.x4_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.x4_lineEdit.setObjectName("x4_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.x4_lineEdit)
        self.x5_label = QtWidgets.QLabel(self.centralwidget)
        self.x5_label.setObjectName("x5_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.x5_label)
        self.x5_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.x5_lineEdit.setObjectName("x5_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.x5_lineEdit)
        self.x6_label = QtWidgets.QLabel(self.centralwidget)
        self.x6_label.setObjectName("x6_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.x6_label)
        self.x6_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.x6_lineEdit.setObjectName("x6_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.x6_lineEdit)
        self.X7_label = QtWidgets.QLabel(self.centralwidget)
        self.X7_label.setObjectName("X7_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.X7_label)
        self.x7_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.x7_lineEdit.setObjectName("x7_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.x7_lineEdit)
        self.empty_label = QtWidgets.QLabel(self.centralwidget)
        self.empty_label.setObjectName("empty_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.empty_label)
        self.y_label = QtWidgets.QLabel(self.centralwidget)
        self.y_label.setObjectName("y_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.y_label)
        self.y_lineEdit = QtWidgets.QLabel(self.centralwidget)
        self.y_lineEdit.setObjectName("y_lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.y_lineEdit)
        self.nn_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.nn_button.sizePolicy().hasHeightForWidth())
        self.nn_button.setSizePolicy(sizePolicy)
        self.nn_button.setObjectName("nn_button")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.nn_button)

        self.graph_button = QtWidgets.QPushButton(self.centralwidget)
        self.graph_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.graph_button.sizePolicy().hasHeightForWidth())
        self.graph_button.setSizePolicy(sizePolicy)
        self.graph_button.setObjectName("graph_button")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.graph_button)
        

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(3, 20, 0, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../icons/neuron.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_button.setIcon(icon)
        self.start_button.setIconSize(QtCore.QSize(30, 30))
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)

        self.Stack.setCurrentWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar) 
        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

         

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Расчет оценки риска ИБ организации"))
        mainWindow.setWindowIcon(QtGui.QIcon(".\\ui\\../icons/main_icon.png"))
        self.x1_label.setText(_translate("mainWindow", "Программно-аппаратный уровень защиты:"))
        self.x2_label.setText(_translate("mainWindow", "Уровень организационной защиты:"))
        self.x3_label.setText(_translate("mainWindow", "Уровень правовой защиты:"))
        self.x4_label.setText(_translate("mainWindow", "Мотивация источника угроз:"))
        self.x5_label.setText(_translate("mainWindow", "Возможности источника угроз: "))
        self.x6_label.setText(_translate("mainWindow", "Рыночная ценность информационного\n"
"ресурса:"))
        self.X7_label.setText(_translate("mainWindow", "Объем данных информационного ресурса\n"
"организации:"))
        self.empty_label.setText(_translate("mainWindow", "TextLabel"))
        self.y_label.setText(_translate("mainWindow", "Риск ИБ организации:"))
        self.nn_button.setText(_translate("mainWindow", "Обучение сети"))
        self.start_button.setText(_translate("mainWindow", "Произвести расчет риска\n"
"ИБ организации"))
        self.graph_button.setText(_translate("mainWindow", "Показать график"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
